#!/usr/bin/env bash
# Build the universal PlaiiinLightOS firmware.
#   Usage: ./scripts/build.sh
#
# There is ONE binary for every device. Per-device hardware (lamp type, LED
# pin, count, matrix size, form factor, WiFi creds) is applied at first-boot
# onboarding via the captive portal / /config page — NOT compiled in. See
# ./scripts/onboard.sh for pushing a profile preset to a device after flash.
#
#   Output: build/dist/plaiiinlight_os-<firmware-version>-app.bin    — OTA
#           build/dist/plaiiinlight_os-<firmware-version>-flash.bin  — USB
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
IDF_DIR="${HOME}/esp/esp-idf"

# --- Version manifest ---------------------------------------------------------
VERSION_FILE="$PROJECT_DIR/version.properties"
FW_VERSION="1.0.0"
API_VERSION="1.0.0"
if [ -f "$VERSION_FILE" ]; then
    while IFS='=' read -r k v; do
        k="$(echo "$k" | tr -d ' \t\r')"
        v="$(echo "$v" | tr -d ' \t\r')"
        case "$k" in
            firmware.version) FW_VERSION="$v" ;;
            api.version)      API_VERSION="$v" ;;
            ""|\#*)           ;;
        esac
    done < "$VERSION_FILE"
else
    echo "warn: $VERSION_FILE missing; using fallbacks $FW_VERSION / $API_VERSION"
fi

# Generated outside build/ so idf.py fullclean can't nuke it mid-build.
VERSION_DEFAULTS="$PROJECT_DIR/.sdkconfig.version.defaults"
cat > "$VERSION_DEFAULTS" <<EOF
# Generated by scripts/build.sh from version.properties — do not edit.
CONFIG_PLAIIIN_FIRMWARE_VERSION="$FW_VERSION"
CONFIG_PLAIIIN_API_VERSION="$API_VERSION"
EOF

# Python env pin — ESP-IDF tools break on stock Python 3.14.
export IDF_PYTHON_ENV_PATH="${IDF_PYTHON_ENV_PATH:-$HOME/.espressif/python_env/idf5.3_py3.12_env}"
# shellcheck disable=SC1091
source "$IDF_DIR/export.sh" > /dev/null 2>&1

cd "$PROJECT_DIR"

export SDKCONFIG_DEFAULTS="$PROJECT_DIR/sdkconfig.defaults;$VERSION_DEFAULTS"

BUILD_DIR="$PROJECT_DIR/build"
SDK_FILE="$PROJECT_DIR/sdkconfig"

echo "=== Building PlaiiinLightOS  firmware=$FW_VERSION  api=$API_VERSION ==="
rm -f "$SDK_FILE" "$SDK_FILE.old"
idf.py -B "$BUILD_DIR" -D SDKCONFIG="$SDK_FILE" fullclean
idf.py -B "$BUILD_DIR" -D SDKCONFIG="$SDK_FILE" build

DIST="$PROJECT_DIR/build/dist"
mkdir -p "$DIST"
STAMPED="plaiiinlight_os-${FW_VERSION}"
cp "$BUILD_DIR/plaiiinlight_os.bin" "$DIST/${STAMPED}-app.bin"

# Merge the full image for USB first-flash at offset 0.
python -m esptool --chip esp32 merge_bin -o "$DIST/${STAMPED}-flash.bin" \
    0x1000   "$BUILD_DIR/bootloader/bootloader.bin" \
    0x8000   "$BUILD_DIR/partition_table/partition-table.bin" \
    0xf000   "$BUILD_DIR/ota_data_initial.bin" \
    0x20000  "$BUILD_DIR/plaiiinlight_os.bin"

# Unstamped convenience symlinks.
ln -sfn "${STAMPED}-app.bin"   "$DIST/plaiiinlight_os-app.bin"
ln -sfn "${STAMPED}-flash.bin" "$DIST/plaiiinlight_os-flash.bin"

echo ""
echo "=== build complete ==="
echo "  OTA app:    $DIST/${STAMPED}-app.bin"
echo "  Full flash: $DIST/${STAMPED}-flash.bin"
