#!/usr/bin/env python3
"""
Phase 35 — generator for the hardcoded-effects framework.

Scans lampos/hardcoded/<FORM>/*.c for two kinds of declarative comments:

    // @effect <name> <default_fps>
    // @param <name> <min>..<max> = <default> <description...>

Emits into build/generated/:

    <effect>_params.h   — index enum + extern live-params array + get/apply json prototypes
    <effect>_params.c   — live params init, JSON serialiser, JSON parser (plus NVS load)
    hardcoded_registry.c — descriptor array (one entry per effect found)

If no effects are found for the form, hardcoded_registry.c is emitted with an
empty array — the firmware compiles and runs fine; /api/js just lists nothing
extra.

The effect's C file is expected to:
  * provide functions named `<effect>_init`, `<effect>_render_frame`, and
    optionally `<effect>_deinit` — matching the hardcoded_effect_t contract
  * `#include "<effect>_params.h"` and reference live params as
    `<effect>_params[<EFFECT>_PARAM_<name>]`
  * declare its decls inside `// @effect`/`// @param` comments at file head

Usage:
    gen_hardcoded.py --form <form> --src-dir <hardcoded_root> --out-dir <generated>
"""
import argparse
import os
import re
import sys
from pathlib import Path

EFFECT_RE = re.compile(r"^\s*//\s*@effect\s+(\S+)\s+(\d+)\s*$")
PARAM_RE  = re.compile(
    r"^\s*//\s*@param\s+(\S+)\s+([-+0-9.eE]+)\.\.([-+0-9.eE]+)\s*=\s*([-+0-9.eE]+)\s+(.*)$"
)


def parse_effect(c_path: Path):
    """Return dict {name, default_fps, params:[{name,min,max,default,desc}]} or None."""
    text = c_path.read_text()
    name = None
    default_fps = 30
    params = []
    for raw in text.splitlines():
        m = EFFECT_RE.match(raw)
        if m:
            if name is not None:
                sys.exit(f"{c_path}: two @effect declarations not allowed")
            name = m.group(1)
            default_fps = int(m.group(2))
            continue
        m = PARAM_RE.match(raw)
        if m:
            params.append({
                "name":    m.group(1),
                "min":     float(m.group(2)),
                "max":     float(m.group(3)),
                "default": float(m.group(4)),
                "desc":    m.group(5).strip(),
            })
    if name is None:
        return None
    return {"name": name, "default_fps": default_fps, "params": params, "src": c_path}


def num_fmt(v: float) -> str:
    """Render a float as compactly as possible while keeping a decimal point."""
    s = f"{v:g}"
    return s


def num_fmt_c(v: float) -> str:
    """C literal with trailing 'f' so the compiler picks float, not double."""
    s = f"{v:g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_params_h(out_dir: Path, eff: dict):
    name = eff["name"]
    upper = name.upper()
    lines = [
        "/* GENERATED by gen_hardcoded.py — do not edit. */",
        "#pragma once",
        "#include <stddef.h>",
        "",
        f"enum {{",
    ]
    for i, p in enumerate(eff["params"]):
        lines.append(f"    {upper}_PARAM_{p['name']} = {i},")
    lines.append(f"    {upper}_PARAM_COUNT = {len(eff['params'])}")
    lines += [
        "};",
        "",
        f"extern float {name}_params[{upper}_PARAM_COUNT];",
        "",
        f"int {name}_get_params_json(char *out, size_t max_len);",
        f"int {name}_apply_params_json(const char *json, size_t len);",
        f"void {name}_params_load_nvs(void);",
        f"void {name}_params_save_nvs(void);",
        "",
    ]
    (out_dir / f"{name}_params.h").write_text("\n".join(lines))


def emit_params_c(out_dir: Path, eff: dict):
    name = eff["name"]
    upper = name.upper()
    n = len(eff["params"])
    lines = [
        "/* GENERATED by gen_hardcoded.py — do not edit. */",
        f'#include "{name}_params.h"',
        '#include "config_store.h"',
        '#include "esp_log.h"',
        '#include <stdio.h>',
        '#include <stdlib.h>',
        '#include <string.h>',
        '',
        f'static const char *TAG = "hc_{name}";',
        '',
    ]
    # defaults init
    defaults = ", ".join(num_fmt_c(p["default"]) for p in eff["params"])
    lines += [
        f"float {name}_params[{upper}_PARAM_COUNT] = {{ {defaults} }};",
        "",
    ]
    # min/max arrays for clamping (private)
    mins = ", ".join(num_fmt_c(p["min"]) for p in eff["params"])
    maxs = ", ".join(num_fmt_c(p["max"]) for p in eff["params"])
    lines += [
        f"static const float s_min[{upper}_PARAM_COUNT] = {{ {mins} }};",
        f"static const float s_max[{upper}_PARAM_COUNT] = {{ {maxs} }};",
        "",
    ]

    # get_params_json
    lines += [
        f"int {name}_get_params_json(char *out, size_t max_len)",
        "{",
        '    int n = snprintf(out, max_len, "{\\"items\\":[");',
        '    if (n < 0 || (size_t)n >= max_len) return 0;',
    ]
    for i, p in enumerate(eff["params"]):
        sep = "," if i > 0 else ""
        # Field name MUST be "description" (matches plbc_params_to_json so the
        # client decoder treats hardcoded effects identically to PLBC ones).
        fmt = (
            f'"{sep}{{\\"name\\":\\"{p["name"]}\\",'
            f'\\"min\\":{num_fmt(p["min"])},'
            f'\\"max\\":{num_fmt(p["max"])},'
            f'\\"default\\":{num_fmt(p["default"])},'
            f'\\"value\\":%g,'
            f'\\"description\\":\\"{c_escape(p["desc"])}\\"}}"'
        )
        lines += [
            f'    n += snprintf(out + n, max_len - n, {fmt}, {name}_params[{i}]);',
            '    if (n < 0 || (size_t)n >= max_len) return 0;',
        ]
    lines += [
        '    n += snprintf(out + n, max_len - n, "]}");',
        '    if (n < 0 || (size_t)n >= max_len) return 0;',
        '    return n;',
        "}",
        "",
    ]

    # apply_params_json — tiny per-name strstr parser
    lines += [
        f"int {name}_apply_params_json(const char *json, size_t len)",
        "{",
        "    (void)len;",
        "    if (!json) return 0;",
        "    int applied = 0;",
        "    const char *p; float v; char *end;",
    ]
    for i, p in enumerate(eff["params"]):
        key_lit = f'"\\""{p["name"]}"\\""'
        lines += [
            f'    p = strstr(json, "\\"{p["name"]}\\"");',
            "    if (p) {",
            "        p = strchr(p, ':');",
            "        if (p) {",
            "            v = strtof(p + 1, &end);",
            "            if (end != p + 1) {",
            f"                if (v < s_min[{i}]) v = s_min[{i}];",
            f"                if (v > s_max[{i}]) v = s_max[{i}];",
            f"                {name}_params[{i}] = v;",
            "                applied++;",
            "            }",
            "        }",
            "    }",
        ]
    lines += [
        f'    if (applied) {{ {name}_params_save_nvs(); }}',
        "    return applied;",
        "}",
        "",
    ]

    # NVS persistence — single string key hc_p_<name>, holds the current JSON
    nvs_key = f"hc_p_{name}"
    # NVS keys are limited to 15 chars. Confirm at build time.
    if len(nvs_key) > 15:
        sys.exit(f"NVS key '{nvs_key}' exceeds 15 chars — rename the effect")
    lines += [
        f"void {name}_params_save_nvs(void)",
        "{",
        "    char buf[512];",
        f"    int n = {name}_get_params_json(buf, sizeof(buf));",
        "    if (n > 0) {",
        f'        config_store_set_str("{nvs_key}", buf);',
        "    }",
        "}",
        "",
        f"void {name}_params_load_nvs(void)",
        "{",
        "    char buf[512];",
        f'    config_get_str_or("{nvs_key}", buf, sizeof(buf), "");',
        "    if (buf[0]) {",
        f"        (void){name}_apply_params_json(buf, strlen(buf));",
        f'        ESP_LOGI(TAG, "params restored from NVS");',
        "    }",
        "}",
        "",
    ]

    (out_dir / f"{name}_params.c").write_text("\n".join(lines))


def emit_registry(out_dir: Path, effects: list, form: str):
    lines = [
        "/* GENERATED by gen_hardcoded.py — do not edit. */",
        '#include "hardcoded_effects.h"',
        '#include <string.h>',
        "",
        f'/* Form: {form} */',
        "",
    ]
    for eff in effects:
        name = eff["name"]
        lines += [
            f'#include "{name}_params.h"',
            f'extern esp_err_t {name}_init(int w, int h);',
            f'extern esp_err_t {name}_render_frame(int w, int h, led_color_t *frame, uint32_t time_ms);',
            f'extern void {name}_deinit(void);  /* may be a no-op stub in the effect */',
            "",
        ]

    for eff in effects:
        name = eff["name"]
        lines += [
            f"static const hardcoded_effect_t s_{name}_desc = {{",
            f'    .name = "{name}",',
            f'    .default_fps = {eff["default_fps"]},',
            f"    .init = {name}_init,",
            f"    .render_frame = {name}_render_frame,",
            f"    .get_params_json = {name}_get_params_json,",
            f"    .apply_params_json = {name}_apply_params_json,",
            f"    .deinit = {name}_deinit,",
            "};",
            "",
        ]

    lines.append("static const hardcoded_effect_t * const g_registry[] = {")
    for eff in effects:
        lines.append(f"    &s_{eff['name']}_desc,")
    if not effects:
        lines.append("    /* empty */")
    lines += [
        "};",
        "",
        "size_t hardcoded_effect_count(void) {",
        "    return sizeof(g_registry) / sizeof(g_registry[0]);",
        "}",
        "",
        "const hardcoded_effect_t *hardcoded_effect_at(size_t i) {",
        "    return i < hardcoded_effect_count() ? g_registry[i] : NULL;",
        "}",
        "",
        "const hardcoded_effect_t *hardcoded_effect_find(const char *name) {",
        "    if (!name) return NULL;",
        "    for (size_t i = 0; i < hardcoded_effect_count(); i++) {",
        "        if (strcmp(g_registry[i]->name, name) == 0) return g_registry[i];",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]
    # Allow no effects (empty registry) — needs to avoid the unused-var warning
    if not effects:
        lines.insert(0, "/* No hardcoded effects compiled in for this form. */")

    (out_dir / "hardcoded_registry.c").write_text("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--form", required=True, help="lamp form (e.g. tower)")
    ap.add_argument("--src-dir", required=True, help="path to lampos/hardcoded")
    ap.add_argument("--out-dir", required=True, help="path to write generated files")
    args = ap.parse_args()

    src_dir = Path(args.src_dir) / args.form
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    effects = []
    if src_dir.is_dir():
        for c_path in sorted(src_dir.glob("*.c")):
            eff = parse_effect(c_path)
            if eff:
                effects.append(eff)
                emit_params_h(out_dir, eff)
                emit_params_c(out_dir, eff)
                print(f"  hardcoded: {eff['name']} ({len(eff['params'])} params)", file=sys.stderr)
    emit_registry(out_dir, effects, args.form)


if __name__ == "__main__":
    main()
